version: '3.9'

services: 
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.dev
    volumes:
      - "/app/node_modules"
      - "./frontend:/app"
    ports:
      - "3000:3000"

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile.dev
    volumes:
      - "/app/node_modules"
      - "./backend:/app"
    ports:
      - "4000:4000"