version: '3.9'

services: 
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.dev
    volumes:
      - "/app/node_modules"
      - "./frontend:/app"
    ports:
      - "3000:3000"

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile.dev
    volumes:
      - "/app/node_modules"
      - "./backend:/app"
    ports:
      - "4000:4000"

  postgres:
    image: postgres:13.1
    restart: always
    volumes:
      - db_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=sammy
      - POSTGRES_PASSWORD=your_password
    ports:
      - "5432:5432"

volumes:
  db_data: